### ISSUE TITLE
Show instructions when password are pulled from secret resources

### ISSUE THREAD

**Issue by etiennetremel** [ContainerSolutions/helm-convert#2]
Currently when a secret type Opaque is pulled from a secret (ie: password), it is converted in plain text and stored in the kustomization.yaml with a `printf` command, ie:

```
secretGenerator:
- commands:
    redis-password: printf \"OYTG9S4SUi\"
  name: sentry-redis
  type: Opaque
```

After the chart is deployed we need to warn the user that there is a plain text password stored there.
